### ISSUE TITLE
[FEATURE] add a upvote or like button - Backend

### ISSUE THREAD

**Issue by rupali-codes** [rohitdasu/projectmate#306]
### Description

Add upvote functionality to the backend of project, count all the upvotes for project, and update count as it grows.

**Comment by zvolcsey** [comment]
Hi, it is an interesting issue. Can I help to implement that?

**Comment by rupali-codes** [comment]
Hi @zvolcsey it's great to have you on ProjectMate, yes you can start working this issue and let us know for any kind of help.

**Comment by zvolcsey** [comment]
Hi, I finished the like functionality. I also worked on the frontend. #305 

One thing is missing: Projects need to be render again after login/logout. In tried the feature in development mode and the page does not render again.
Should I work on this or make a PR now to review the functionality?

Summary of  the solution:

Backend

I added this model to the `schema.prisma` file and linked it to the other models.

```prisma
model Like {
  id          String   @id @default(auto()) @map("_id") @db.ObjectId
  user        User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId      String   @db.ObjectId
  project     Project  @relation(fields: [projectId], references: [id], onDelete: Cascade)
  projectId   String   @db.ObjectId
  createdAt   DateTime @default(now())

  @@unique([userId, projectId])
}
```

`POST - /api/project/:postId/like` route
1. getServerAuthSession
2. find the reqUser - Like document needs the userId
3. getPostById
4. check - the project does not belong to the logged User - if YES=> throw Error
5. check - the project is liked or not - find like in the Like collection  if YES=> throw Error
6. like the project
- create a like document and update the likesCount property in the Project collection in a transaction

`DELETE - /api/project/:postId/like` route
1. getServerAuthSession
2. find the reqUser - Like document need the userId
3. getPostById
4. check - the project does not belong to the logged logged User - if YES => throw Error
5. check - the project is liked or not - find like in the Like collection  if NO => throw Error
6. unlike the project
- delete the like document and update the likesCount property in the Project collection in a transaction

update `getAllProject`, `getPostById` function
- find the project/projects and if there is a logged User, then change the liked  value - if the logged User liked this project

`getProject` function is unchanged, because it returns the loggedUser`s projects and the liked property always false

Frontend

- Add like button and likesCount span element to the `Project.tsx` file.
- Update the `ProjectSkeleton.tsx` file.


![projectmate](https://user-images.githubusercontent.com/41576384/211323730-3fa7e275-9317-4479-b184-daad178fe50f.png)

**Comment by rohitdasu** [comment]
Hi @zvolcsey could you pls raise a PR. Would love to see
