### ISSUE TITLE
[FEATURE] ability to delete our projects

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#335]
### Description

in profile page, we already have delete button. that's not working. we need to make it working. when we click on that delete button, a popup should open with a confirmation message to delete it or not. if user clicks on delete/ok button then it will delete the project.

**Comment by MaruthiKo** [comment]
Hi
I would love to work on this issue

**Comment by rohitdasu** [comment]
> Hi
> 
> I would love to work on this issue
> 
> 

Sure, proceed 👍

**Comment by naman267** [comment]
@MaruthiKo are you still working on this issue or can I give it a shot? @rohitdasu

**Comment by rohitdasu** [comment]
hi @JakubChorzepa are you working on this issue? if not let's assign it to @naman267

**Comment by naman267** [comment]
is he working on it ? @rohitdasu

**Comment by rohitdasu** [comment]
> is he working on it ? @rohitdasu

yes, as far i know @JakubChorzepa is working on this issue.

**Comment by JakubChorzepa** [comment]
I was about to work on this issue but due to lack of time you can take it @naman267. I'll take other issue in free time

**Comment by rohitdasu** [comment]
Thanks for the update @JakubChorzepa 

@naman267 please work on this issue, let us know if you need anything

**Comment by naman267** [comment]
Thanks @rohitdasu  @JakubChorzepa

**Comment by naman267** [comment]
![image](https://user-images.githubusercontent.com/57058345/230040596-5eae1aa0-dad8-4f60-bedd-38f85b8f383e.png)

@rohitdasu is this popup ok or is there any change that you would like to suggest ?

**Comment by rohitdasu** [comment]
> ![image](https://user-images.githubusercontent.com/57058345/230040596-5eae1aa0-dad8-4f60-bedd-38f85b8f383e.png)
> 
> @rohitdasu is this popup ok or is there any change that you would like to suggest ?

this looks ok to me. just make sure yes and no button colors(red and green) match with edit and delete button

**Comment by naman267** [comment]
actually I made the Yes button red to signal some kind of danger (deleting the project), I will switch their colors thanks :)

**Comment by naman267** [comment]
@rohitdasu I have implemented the delete functionality, but after deleting a user project the profile should be updated with remaining projects, so for doing this we can reload the page using router.reload  do you want me to implement me in this way?

**Comment by rohitdasu** [comment]
> 

don't reload it. when the delete operation is successful just fetch the projects data and update the projects array which is rendered.

**Comment by naman267** [comment]
![image](https://user-images.githubusercontent.com/57058345/230357177-920ede3f-badc-482c-a3a0-5f1b97df052b.png)
![image](https://user-images.githubusercontent.com/57058345/230357220-fdcf9a5f-ca24-4137-85e5-9ffaa52490e5.png)
![image](https://user-images.githubusercontent.com/57058345/230357252-b7a6d2b7-5cd8-4901-98e1-1211a1a7f60a.png)

I have created the delete functionality upon clicking the Yes button and the profile page will get re-rendered with updated projects list. For this functionality I had to make some changes listing down
1) I had to implement state managment in  "/pages/user/profile" using useState and useEffect hook so that I can store the lists of project as state and whenever a project is deleted ,I can update the state and the page gets re-rendered
2) I had to pass props to UserBio component inside Profile page component because easrlier there as no props getting passed in UserBio component it was fetching the data from API because of which the project numbers section in profile page was not getting updated when the project got deleted because when user Profile got re-rendered the child component UserBio didnt get re-rendered as there was no suspectible change in it . So to make it re-rendered I passed projectNumbers  as a props , so whenever profile page state gets updated, projectsNumber also get changed and UserBio component gets re-rendered
3)Created a delete api in api/user/project file
4)Created the functionality of popup 


If this seems correct to you, so can I raise the PR or is there any change that you would like to suggest
